# HTTP-specific options
http:

  port: 8080
  adminPort: 8081


# Logging
logging:

  level: INFO

  loggers:
    # Set debug logging for our code
    "uk.co.flax": DEBUG
    
classifier: classifiers/english.muc.7class.distsim.crf.ser.gz

  