
# Path to authentication file
authenticationFile: /home/mlp/.twitter.oauth

# Path to data directory
dataDirectory: /home/mlp/ukmp/data

# Path to archive directory
archiveDirectory: /home/mlp/ukmp/archive

# Number of listeners to run
numListeners: 4

# Number of processor threads
numThreads: 4

# Size of incoming message queue
messageQueueSize: 1000

# Parties
parties: 
  labour:
    displayName: Labour
    twitterScreenName: tweetminster
    twitterListSlug: labour

  conservative:
    displayName: Conservative
    twitterScreenName: tweetminster
    twitterListSlug: conservatives

  libdem:
    displayName: Liberal Democrat
    twitterScreenName: tweetminster
    twitterListSlug: libdems

  other:
    displayName: Other
    twitterScreenName: tweetminster
    twitterListSlug: others
    